import 'package:flutter/material.dart';

/// The basemap every full-screen map and map preview in the app draws.
///
/// One semantic source for the style decision, so no screen hardcodes a style
/// of its own and no screen is left on a Light-only basemap:
///
/// - Light app theme → [lightStyleAsset], the **App Light Map**
/// - Dark app theme → [darkStyleAsset], the **App Dark Map**
///
/// The choice is semantic and costs nothing at runtime — it is the app's own
/// `Theme.of(context).brightness`, never an analysis of what the tiles happen
/// to look like. The status-bar glyphs over a map follow the same input via
/// `StatusBarBackdrop.ofTheme` (see `system_status_bar.dart`), which is what
/// keeps the two in step: a dark basemap always carries white glyphs.
///
/// ## Why the styles are ours, and bundled
///
/// Both styles are MapLibre style documents the app owns and ships as assets,
/// generated by `tool/build_map_styles.js` from one vendored upstream
/// structure (`tool/map_styles/liberty.upstream.json`, OpenFreeMap "liberty").
/// The generator rewrites **paint only** — colours — and leaves the sources,
/// glyphs, sprite, `source-layer`s, filters, zoom stops and layer order exactly
/// as upstream. Two consequences worth keeping in mind:
///
/// - Light and Dark have an *identical* layer list, so the road hierarchy and
///   the label hierarchy cannot drift apart between themes. A provider's own
///   dark style is a different, thinner document; ours is not.
/// - Nothing about the map data changes. The tiles are still the same key-free
///   `tiles.openfreemap.org/planet` vector source, and the style files carry
///   the OpenFreeMap / OpenMapTiles / OpenStreetMap attribution explicitly.
///
/// The palettes themselves are documented in
/// `UI_TRANSFER_PACKAGE/docs/01_DESIGN_SYSTEM_CANONICAL.md` §7.2. To change a
/// map colour, edit the palette in `tool/build_map_styles.js` and re-run it —
/// never hand-edit the generated JSON.
abstract final class AppMapStyle {
  /// The **App Light Map** — warm ivory land, pale teal water, sage parks and
  /// a warm-sand road hierarchy, with navy place labels.
  static const String lightStyleAsset = 'assets/map_styles/app_light.json';

  /// The **App Dark Map** — deep charcoal-teal land, deep blue-teal water,
  /// dark muted green parks and a gray-teal road hierarchy, with off-white
  /// place labels. Not a provider default: a real style in the app's own dark
  /// design language.
  ///
  /// A real basemap style, deliberately: darkening the light map with an
  /// overlay, an opacity layer or a colour filter would take the labels and
  /// the road hierarchy down with it.
  static const String darkStyleAsset = 'assets/map_styles/app_dark.json';

  /// The style for an already-resolved brightness.
  static String forBrightness(Brightness brightness) =>
      brightness == Brightness.dark ? darkStyleAsset : lightStyleAsset;

  /// The style for the ambient app theme — what every map widget should call.
  /// Reading it inside `build` is what makes a map follow a Light↔Dark switch
  /// without a restart.
  static String of(BuildContext context) =>
      forBrightness(Theme.of(context).brightness);
}
