// Exports the bundled Help & Support content to JSON for the seed script.
//
// `bundledHelpFaqs` in lib/models/help_faq.dart is the single source of truth
// for this content. Node cannot read Dart, so rather than transcribing forty
// question/answer pairs into the seed script by hand — which is how two copies
// start disagreeing — this regenerates the JSON the seeder reads.
//
//   dart run tool/export_help_topics.dart
//
// Writes tool/help_topics_seed.json in the exact shape DATA_MODEL.md
// documents for `help_topics`.
import 'dart:convert';
import 'dart:io';

import 'package:kurdistan_paradise_travel_guide/models/help_faq.dart';
import 'package:kurdistan_paradise_travel_guide/models/help_topic.dart';

void main() {
  final out = <String, Object?>{
    '_comment':
        'GENERATED by tool/export_help_topics.dart from '
        'lib/models/help_faq.dart. Do not edit by hand — edit the Dart '
        'bundled content and re-run the exporter, or the app and Firestore '
        'will disagree.',
  };

  for (final (index, topic) in HelpTopic.values.indexed) {
    final entries = bundledHelpFaqsFor(topic);
    out[topic.docId] = <String, Object?>{
      // 1-based, matching the order the screen draws the rows in.
      'order': index + 1,
      'active': true,
      'content': <String, Object?>{
        // English only — that is all the bundled content has. A missing locale
        // falls back to `en`, the same rule as legal_documents.
        'en': <String, Object?>{
          'questions': [
            for (final entry in entries)
              <String, Object?>{
                'question': entry.question,
                'answer': entry.answer,
              },
          ],
        },
      },
    };
  }

  final file = File('tool/help_topics_seed.json');
  file.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(out)}\n',
  );

  final topics = HelpTopic.values.length;
  final questions = HelpTopic.values
      .map((t) => bundledHelpFaqsFor(t).length)
      .reduce((a, b) => a + b);
  stdout.writeln(
    'Wrote ${file.path}: $topics topics, $questions questions total.',
  );
}
