// Exports the preview rental catalogue to JSON for the seed script.
//
//   flutter test tool/export_cars.dart
//
// Run through the Flutter test harness rather than `dart run`, because the
// rental models import package:flutter for @immutable. It lives under tool/
// and not test/, so the default `flutter test` run never picks it up.
//
// Output shape is exactly the revised `cars` and `rental_locations` schemas in
// DATA_MODEL.md.
//
// ## What is deliberately NOT exported
//
// * **`conditions`** — fuel policy, deposit, damage excess, cancellation
//   deadline, minimum driver age and required documents are contractual and
//   financial terms a renter acts on. `PreviewCarRentalService` leaves them
//   entirely empty on purpose (SEED_DATA.md) and nothing here invents them.
//   The Rental Conditions card stays hidden until a supplier feed fills them.
// * **`imageUrls` is written empty**, matching hotels, nature_spots and tours.
//   The preview gallery repeats one bundled asset so the carousel can be
//   exercised; those are asset paths, not the Storage URLs the field documents.
// * **No IQD prices are fabricated.** Every preview vehicle is quoted in USD,
//   so every seeded vehicle carries `currencyCode: "USD"` and its real figure.
//   A vehicle's authoritative price is whatever its supplier quotes; inventing
//   a second currency would invent a rate nobody honours.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:kurdistan_paradise_travel_guide/models/car_rental.dart';
import 'package:kurdistan_paradise_travel_guide/services/car_rental_service.dart';

Map<String, Object?> text(RentalText t) => {'en': t.en, 'ku': t.ku, 'ar': t.ar};

Map<String, Object?> extra(RentalExtra e) => {
  'id': e.id,
  'name': text(e.name),
  'pricePerDay': e.pricePerDay,
  'selection': e.selection.name,
  'minQuantity': e.minQuantity,
  'maxQuantity': e.maxQuantity,
};

Map<String, Object?> branch(RentalLocation l) => {
  'name': text(l.name),
  'city': text(l.city),
  'country': text(l.country),
  if (l.airportCode != null) 'airportCode': l.airportCode,
  'location': {'lat': l.latitude, 'lng': l.longitude},
  'active': true,
};

Map<String, Object?> car(RentalVehicle v) => {
  'name': text(v.name),
  'year': v.modelYear,
  // Replaces the old flat rentalCompany/companyTag pair, which could not carry
  // a localized company name.
  'company': {'id': v.company.id, 'name': text(v.company.name)},
  'imageUrls': <String>[],
  'capacity': v.passengers,
  'fuelType': v.powertrain.name,
  'bags': v.bags,
  'hasAC': v.airConditioning,
  'paymentInfo': v.paymentOption.name,
  'locationId': v.location.id,
  // The authoritative price, in the currency the supplier quotes. Never a
  // second converted copy — see DATA_MODEL.md.
  'pricePerDay': v.dailyPrice,
  'currencyCode': v.currencyCode,
  'featured': v.featured,
  'active': true,
  'transmission': v.transmission.name,
  'extras': [for (final e in v.extras) extra(e)],
};

void main() {
  test('export the preview rental catalogue to tool/cars_seed.json', export);
}

Future<void> export() async {
  final cars = <String, Object?>{};
  final locations = <String, Object?>{};

  for (final v in PreviewCarRentalService.vehicles) {
    cars[v.id] = car(v);
  }
  for (final l in PreviewCarRentalService.locations) {
    locations[l.id] = branch(l);
  }

  // Guard the currency contract at export time, so a bad value can never reach
  // the seeder — the rules would reject it, but failing here names the vehicle.
  for (final entry in cars.entries) {
    final code = (entry.value! as Map)['currencyCode'];
    if (code != 'USD' && code != 'IQD') {
      throw StateError('${entry.key} has unsupported currency "$code"');
    }
  }

  final out = <String, Object?>{
    '_comment':
        'GENERATED by tool/export_cars.dart from PreviewCarRentalService. '
        'Do not edit by hand — edit the Dart preview data and re-run the '
        'exporter. conditions and imageUrls are deliberately omitted/empty, '
        'and no IQD price is fabricated; see the exporter header.',
    'cars': cars,
    'rental_locations': locations,
  };

  final file = File('tool/cars_seed.json');
  file.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(out)}\n',
  );

  final currencies = <String>{
    for (final c in cars.values) (c! as Map)['currencyCode'] as String,
  };
  stdout.writeln(
    'Wrote ${file.path}: ${cars.length} cars, ${locations.length} branches. '
    'Currencies present: ${currencies.join(', ')}.',
  );
}
